Fixed issue taking exactly 6 arguments (5 given)
Running 'pp_run all' fails with error

File "photometrypipeline/pp_run", line 406, in <module>
fixed_aprad, source_tolerance)
TypeError: run_the_pipeline() takes exactly 6 arguments (5 given)

because solar argument is missing.